#!/usr/bin/env bash

SESSION='Bachelor'

tmux -2 new-session -d -s $SESSION

# Set up first window.
tmux rename-window -t $SESSION 'Development'
tmux send-keys 'cd src/ ; vim main.c' C-m

# Make test window.
tmux new-window -t $SESSION:1 -n 'Test'
tmux send-keys 'cd test' C-m
tmux send-keys 'cd test' C-m
tmux split-window -h
tmux select-pane -t 0
tmux send-keys 'vim' C-m

# Attach to the new session.
tmux select-window -t $SESSION:0
tmux -2 attach-session -t $SESSION
